sequenceDiagram
    actor Ejer as Actor
    participant UI
    participant ViewModel
    participant Infrastructure

    Ejer->>UI: NavigateTo("ManagesShelfTypes")
    UI->>ViewModel: OnNavigateToShelfTypes()
    loop
        ViewModel->>Infrastructure: GetAllAsync()
        Infrastructure-->>ViewModel: Task<IEnumerable<ShelfType>>
        ViewModel-->>UI: ShelfTypeListViewModel(ObservableCollection<ShelfType>)

        alt Add ShelfType
            Ejer->>UI: CreateShelfType(string: name, string: description)
            alt Tilføj
                UI->>ViewModel: OnAddAsync()
                ViewModel->>Infrastructure: AddAsync({name, description})
                Infrastructure-->>ViewModel: Task
                ViewModel-->>ViewModel: InfoMessage(_infoMsgSuccesSave)
            else Annuller
                UI->>ViewModel: OnCancelAsync()
                ViewModel-->>UI: OnPropertyChange() # Populate form fields and pop listVm and Messages
            else Reol type navn er ikke unik
                UI->>ViewModel: CanAdd() : false
                ViewModel-->>ViewModel: ErrorMessage(_errorMsgNameNotUnique)
                ViewModel-->>UI: OnPropertyChange() # Populate form fields and pop listVm and Messages
            else Systemfejl under oprettelse
                UI->>ViewModel: OnAddAsync()
                ViewModel->>Infrastructure: AddAsync({name, description})
                Infrastructure-->>ViewModel: Exception # It logs error before Exception
                ViewModel-->>ViewModel: ErrorMessage(_errorMsgCreateFailed)
                ViewModel-->>UI: OnPropertyChange() # Populate form fields and pop listVm and Messages
            end
            ViewModel-->>UI: OnPropertyChange() # Populate form fields and pop listVm and Messages
        else Select ShelfType
            Ejer->>UI: SelectShelfType(Guid: shelfTypeId)
            UI->>ViewModel: OnShelfTypeSelected(Guid: shelfTypeId)
            ViewModel->>Infrastructure: GetByIdAsync(Guid: shelfTypeId)
            Infrastructure-->>ViewModel: Task<ShelfType>
            ViewModel-->>UI: OnPropertyChange() # Populate form fields and pop listVm and Messages

            alt Edit ShelfType
                alt succes
                    Ejer->>UI: EditShelfType(Guid: shelfTypeId, string: name, string: description)
                    UI->>ViewModel: OnSaveAsync()
                    ViewModel->>Infrastructure: UpdateAsync(Guid: shelfTypeId, {name, description})
                    Infrastructure-->>ViewModel: Task
                    ViewModel-->>UI: OnPropertyChange() # Populate form fields and pop listVm and Messages
                else Valgt annullere
                    Ejer->>UI: OnCancel()
                    UI->>ViewModel: OnCancelAsync()
                    ViewModel-->>UI: OnPropertyChange() # Populate clear fields and pop listVm and Messages
                else ReolNavn er ikke unik
                    UI->>ViewModel: CanSave() : false
                    ViewModel-->>ViewModel: ErrorMessage(_errorMsgNameNotUnique)
                else Systemfejl under gemning
                    Ejer->>UI: EditShelfType(string: name, string: description)
                    UI->>ViewModel: OnSaveAsync()
                    ViewModel->>Infrastructure: UpdateAsync(ShelfType: entity)
                    Infrastructure-->>ViewModel: Exception # It logs error before Exception
                    ViewModel-->>ViewModel: ErrorMessage(_errorMsgSaveFailed)
                    ViewModel-->>UI: OnPropertyChange() # Populate form fields and pop listVm and Messages
                end
            else Delete ShelfType
                Ejer->>UI: RequestDeleteShelfType(Guid: shelfTypeId)
                alt ReolType kan slettes (ingen afhængigheder)

                UI->>ViewModel: OnDeleteAsync()
                ViewModel->>Infrastructure: DeleteAsync(Guid: shelfTypeId)
                else ReolType kan ikke slettes (har afhængigheder)
                    UI->>ViewModel: OnDeleteAsync()
                    ViewModel->>Infrastructure: DeleteAsync(Guid: shelfTypeId)
                    Infrastructure-->>ViewModel: Exception # It logs error before Exception
                    ViewModel-->>ViewModel: ErrorMessage(_errorMsgDeleteHasDependencies)
                    ViewModel-->>UI: OnPropertyChange() # Populate form fields and pop listVm and Messages
                else Systemfejl under sletning
                    UI->>ViewModel: OnDeleteAsync()
                    ViewModel->>Infrastructure: DeleteAsync(Guid: shelfTypeId)
                    Infrastructure-->>ViewModel: Exception # It logs error before Exception
                    ViewModel-->>ViewModel: ErrorMessage(_errorMsgDeleteFailed)
                    ViewModel-->>UI: OnPropertyChange() # Populate form fields and pop listVm and Messages
                end
                Infrastructure-->>ViewModel: Task
                ViewModel-->>UI: OnPropertyChange() # Populate clear fields and pop listVm and Messages
            end
        end
    end
    Ejer->>UI: NavigateTo("FrontPageView")
    UI->>ViewModel: OnNavigateToFrontPage()
    ViewModel-->>UI: FrontPageViewModel
    ViewModel-->>UI: OnPropertyChange() # Populate form fields and pop listVm and Messages
    UI-->>Ejer: FrontPageView