sequenceDiagram
    actor Ejer as Actor
    participant UI
    participant ViewModel
    participant Infrastructure

    Ejer->>UI: NavigateTo("Shelf Types")
    UI->>ViewModel: OnNavigateToShelfTypes()
    ViewModel->>Infrastructure: GetAllAsync()
    Infrastructure-->>ViewModel: Task<IEnumerable<ShelfType>>
    ViewModel-->>UI: ShelfTypeListViewModel(ObservableCollection<ShelfType>)

    alt Add ShelfType
        Ejer->>UI: CreateShelfType(string: name, string: description)
        UI->>ViewModel: AddShelfType(string: name, string: description)
        ViewModel->>Infrastructure: AddAsync({name, description})
        Infrastructure-->>ViewModel: SaveConfirmation
        ViewModel-->>UI: InfoMessage(_infoMsgSuccesSave)
        ViewModel-->>UI: Refresh()
    else Select ShelfType
        Ejer->>UI: SelectShelfType(Guid: shelfTypeId)
        UI->>ViewModel: OnShelfTypeSelected(Guid: shelfTypeId)
        ViewModel->>Infrastructure: GetByIdAsync(Guid: shelfTypeId)
        Infrastructure-->>ViewModel: ShelfTypeDetails
        ViewModel-->>UI: DisplayShelfTypeDetails(ShelfTypeDetails)

        alt Edit ShelfType
            Ejer->>UI: EditShelfType(Guid: shelfTypeId, string: name, string: description)
            UI->>ViewModel: UpdateShelfType(Guid: shelfTypeId, string: name, string: description)
            ViewModel->>Infrastructure: UpdateAsync(Guid: shelfTypeId, {name, description})
            Infrastructure-->>ViewModel: UpdateConfirmation
            ViewModel-->>UI: ShowUpdateConfirmation()
            ViewModel-->>UI: RefreshShelfTypeDetails()
        else Delete ShelfType
            Ejer->>UI: RequestDeleteShelfType(Guid: shelfTypeId)
            UI->>ViewModel: DeleteShelfType(Guid: shelfTypeId)
            ViewModel->>Infrastructure: RemoveShelfType(Guid: shelfTypeId)
            Infrastructure-->>ViewModel: DeleteConfirmation
            ViewModel-->>UI: ShowDeleteConfirmation()
            ViewModel-->>UI: RefreshShelfTypeList()
        end
    end