sequenceDiagram
    actor Ejer
    participant System

    Ejer->>+System: navigererTilAdminReolType()

    loop for valg af handling (tilføj, rediger, slet)

        alt tilføj mode

            alt ReolNavn er unik og type er valgt
                System-->>Ejer: TilføjKnap
                Ejer->>System: Tilføj(ReolNavn, Beskrivelse)
                System-->>Ejer: SuccesBesked
                System-->>Ejer: Nulstil
            else Valgt Nulstil
                Ejer->>System: Nulstil()
            else Reol type navn er ikke unik
                System-->>Ejer: Fejlmeddelelse
            else Systemfejl under oprettelse
                System-->>-Ejer: Fejlmeddelelse
            end

        end

        alt rediger mode vælges

            Ejer->>+System: Rediger(ReolTypeId)
            System-->>Ejer: ReolNavn, ReolBeskrivelse

            alt ReolNavn er unik og type er valgt
                System-->>Ejer: GemKnap
                Ejer->>System: Gem(ReolTypeId, ReolNavn, ReolBeskrivelse)
                System-->>Ejer: SuccesBesked
                System-->>Ejer: Nulstil
            else Valgt annullere
                Ejer->>System: Annulere()
                System-->>Ejer: TilføjMode
            else ReolNavn er ikke unik
                System-->>Ejer: Fejlmeddelelse
            else Systemfejl under oprettelse
                System-->>-Ejer: Fejlmeddelelse
            end

        end

        alt sletning vælges
            Ejer->>+System: slet(ReolId)
            alt ReolType kan slettes (ingen afhængigheder)
                System-->>Ejer: SuccesBesked
                System-->>Ejer: Nulstil
            else ReolType kan ikke slettes (har afhængigheder)
                System-->>Ejer: Fejlmeddelelse
            else Systemfejl under sletning
                System-->>Ejer: Fejlmeddelelse
            end
        end

        alt navigerer væk fra reol-administrationssiden
            Ejer->>+System: NavigerTilForside()
        end
    end
