classDiagram
    class ShelfRentContract {
        +Guid Id
        +Guid ShelfTenantId
        +uint ContractNumber
        +date StartDate
        +date EndDate
        +date CancelledAt
    }

    class ShelfRentContractLine {
        +Guid Id
        +Guid ShelfRentContractId
        +Guid ShelfId
        +uint LineNumber
        +decimal PricePerMonth
        +decimal PricePerMonthSpecial
    }

ShelfRentContract *-- ShelfRentContractLine : "has"

note for ShelfRentContractLine "A contract can have multiple lines, each with different start and end months as well as prices.<br>The price is calculated by default and has some conditions"
