classDiagram
    class ShelfRentContract {
        +Guid Id
        +uint ContractNumber
        +date StartMonth
        +date EndMonth
        +date Cancelled
    }

    class ShelfRentContractLine {
        +Guid Id
        +Guid ShelfRentContractId
        +Guid ShelfId
        +uint LineNumber
        +decimal MonthlyAgreementPrice
        +decimal MonthlyAgreementPriceSpecial
    }

ShelfRentContract *-- ShelfRentContractLine : "has"

note for ShelfRentContractLine "A contract can have multiple lines, each with different start and end months as well as prices.<br>The price is calculated by default and has some conditions"
