erDiagram
    SHELFRENTCONTRACT {
        Guid Id PK
        Guid ShelfTenantId FK
        uint ContractNumber "UNIQUE"
        Date StartDate
        Date EndDate
        Date Cancelled
    }

    SHELFRENTCONTRACTLINE {
        Guid Id PK
        Guid ShelfRentContractId FK
        Guid ShelfId FK
        uint LineNumber "UNIQUE"
        Decimal MonthlyAgreementPrice
        Decimal MonthlyAgreementPriceSpecial
    }

    SHELFRENTCONTRACT ||--o{ SHELFRENTCONTRACTLINE : has