erDiagram
    SHELFTTYPE {
        Guid Id PK
        string Name
        string Description
    }

    SHELF {
        Guid Id PK
        int Number
        Guid ShelfTypeId FK
    }

    SHELFTTYPE ||--o{ SHELF : "has"