classDiagram
    namespace ShelfMarket.Domain.Entities {
        class ShelfType {
            +Guid Id
            +string Name
            +string Description
        }

        class Shelf {
            +Guid Id
            +int Number
            +Guid ShelfTypeId
            +uint LocationX
            +uint LocationY
            +bool OrientationHorizontal
        }

        class ShelfTenantContract {
            +Guid Id
            +Guid ShelfTenantId
            +uint ContractNumber
            +DateTime StartDate
            +DateTime EndDate
            +nullable~DateTime~ CancelledAt
        }

        class ShelfTenantContractLine {
            +Guid Id
            +Guid ShelfTenantContractId
            +Guid ShelfId
            +uint LineNumber
            +decimal PricePerMonth
            +decimal PricePerMonthSpecial
        }
    }

    namespace ShelfMarket.Application.Interfaces {
        class IRepository~TEntity~ {
            <<interface>>
            +GetByIdAsync(Guid id) Task~TEntity~
            +GetAllAsync() Task~List__TEntity~
            +AddAsync(TEntity entity) Task
            +UpdateAsync(TEntity entity) Task
            +DeleteAsync(Guid id) Task
        }
        class IShelfTypeRepository {
            <<interface>>
            +GetByIdAsync(Guid id) Task~ShelfType~
            +GetAllAsync() Task~List__ShelfType~
            +AddAsync(ShelfType shelfType) Task
            +UpdateAsync(ShelfType shelfType) Task
            +DeleteAsync(Guid id) Task
        }

        class IShelfRepository {
            <<interface>>
            +GetByIdAsync(Guid id) Task~Shelf~
            +GetAllAsync() Task~List__Shelf~
            +AddAsync(Shelf shelf) Task
            +UpdateAsync(Shelf shelf) Task
            +DeleteAsync(Guid id) Task
        }

        class IShelfTenantContractRepository {
            <<interface>>
            +GetByIdAsync(Guid id) Task~ShelfTenantContract~
            +GetAllAsync() Task~List__ShelfTenantContract~
            +AddAsync(ShelfTenantContract shelfTenantContract) Task
            +UpdateAsync(ShelfTenantContract shelfTenantContract) Task
            +DeleteAsync(Guid id) Task
        }

        class IShelfTenantContractLineRepository {
            <<interface>>
            +GetByIdAsync(Guid id) Task~ShelfTenantContractLine~
            +GetAllAsync() Task~List__ShelfTenantContractLine~
            +AddAsync(ShelfTenantContractLine shelfTenantContractLine) Task
            +UpdateAsync(ShelfTenantContractLine shelfTenantContractLine) Task
            +DeleteAsync(Guid id) Task
        }
    }

    namespace ShelfMarket.Infrastructure.Repositories {
        class Repository~TEntity~ {
            #ShelfMarketDbContext _context
            #DbSet~TEntity~ _dbSet
            +Repository() void
            +SaveChangesAsync(ShelfMarketDbContext context) Task
        }

        class ShelfRepository {
            +ShelfRepository(ShelfMarketDbContext context)
            +GetByIdAsync(Guid id) Task~Shelf~ 
            +GetAllAsync() Task~List__Shelf~ 
            +AddAsync(Shelf shelf) Task
            +UpdateAsync(Shelf shelf) Task
            +DeleteAsync(Guid id) Task
        }

        class ShelfTypeRepository {
            +ShelfTypeRepository(ShelfMarketDbContext context)
            +GetByIdAsync(Guid id) Task~ShelfType~
            +GetAllAsync() Task~List__ShelfType~
            +AddAsync(ShelfType shelfType) Task
            +UpdateAsync(ShelfType shelfType) Task
            +DeleteAsync(Guid id) Task
        }
    }

    %% Associations
    Shelf --* ShelfRepository : manages
    ShelfType --* ShelfTypeRepository : manages
    ShelfTenantContract --* ShelfTenantContractRepository : manages
    ShelfTenantContractLine --* IShelfTenantContractLineRepository : manages

    %% Composition
    Shelf --* ShelfType : has a
    ShelfTenantContract *-- ShelfTenantContractLine : has
    
    Repository o-- ShelfMarketDbContext : uses


    %% Inheritance and Implementation
    ShelfRepository --|> IShelfRepository : implements
    ShelfTypeRepository --|> IShelfTypeRepository : implements
    ShelfTenantContractRepository --|> IShelfTenantContractRepository : implements
    Repository --|> IRepository : implements

    IShelfRepository --|> IRepository : implements
    IShelfTypeRepository --|> IRepository : implements
    IShelfTenantContractRepository --|> IRepository : implements

    ShelfRepository ..|> Repository : inheritance
    ShelfTypeRepository ..|> Repository : inheritance
    ShelfTenantContractRepository ..|> Repository : inheritance

