classDiagram
    class Reol {
        nummer
    }
    class ReolType {
        navn
        beskrivelse
    }

    class ReolLejeKontrakt {
        KontraktNummer
        StartMåned
        SlutMåned
        Anulleret
    }

    class ReolLejeKontraktLinje {
        LinjeNummer
        MånedligPris
        MånedligAftalePris
    }

    class Moms {
      navn
      procent
      gyldigFra
      gyldigTil
    }

    class Salgskvittering {
      kvitteringsNummer
      udstedtDato
      totalBeloeb
      momsBeloeb
      betaltKontant
      betaltMobil
    }

    class SalgskvitteringLinie {
      Reolnummer
      enhedsPris
    }

    class Avance {
        +avanceProcent
        +gyldigFra
        +gyldigTil
    }

    Reol * -- 1 ReolType : har
    ReolLejeKontrakt * -- 1 ReolLejeKontraktLinje : har
    Salgskvittering 1 -- * SalgskvitteringLinie : indeholder
    Moms 1 -- * SalgskvitteringLinie : anvender sats
    SalgskvitteringLinie * -- 1 Avance : avance
    Reol 1 -- * ReolLejeKontrakt : lejes
    SalgskvitteringLinie * -- 1 Reol : for