erDiagram
    VERSION {
        int Id PK
        Date AppliedAt
    }

    SHELFTYPE {
        Guid Id PK 
        string Name "UNIQUE"
        string Description
    }

    SHELF {
        Guid Id PK
        int Number "UNIQUE"
        Guid ShelfTypeId FK
    }

    SHELFTENANTCONTRACT {
        Guid Id PK
        Guid ShelfTenantId FK
        uint ContractNumber "UNIQUE"
        Date StartDate
        Date EndDate
        Date Cancelled
    }

    SHELFTENANTCONTRACTLINE {
        Guid Id PK
        Guid ShelfTenantContractId FK
        Guid ShelfId FK
        uint LineNumber "UNIQUE"
        Decimal MonthlyAgreementPrice
        Decimal MonthlyAgreementPriceSpecial
    }

    SHELFTYPE ||--o{ SHELF : has
    SHELFTENANTCONTRACT ||--o{ SHELFTENANTCONTRACTLINE : has